print('Hellow Workd!')
print('What is your name?')
myName=input()
print('It is good to meet you,' + myName)
print('The length of your name is:')
print(len(myName))
print('Whitch year was your born?')
myYear =input()
print('You has been '+ str(2020 - int(myYear)) + 'days.')
